[font]
size = 9

[font.normal]
family = "JetBrainsMono NF"

[cursor.style]
shape = "Beam"

[window]
decorations = "None"
dynamic_padding = true
padding = { x = 3, y = 3 }

[colors.primary]
background = "#1D1D20"
foreground = "#BABABA"

[colors.normal]
black = "#000000"
red = "#E05A4F"
green = "#68C256"
yellow = "#DCCD51"
blue = "#2387D9"
magenta = "#8E69C9"
cyan = "#2387D9"
white = "#BABABA"

[colors.bright]
black = "#666666"
red = "#E05A4F"
green = "#77B869"
yellow = "#EFD64B"
blue = "#4AA3E8"
magenta = "#957BBE"
cyan = "#4AA3E8"
white = "#BABABA"

[colors.cursor]
cursor = "#a6a28c"
text = "#20201d"
