[colors.primary]
background = "#232326"
foreground = "#BABABA"

[colors.normal]
black = "#000000"
red = "#E05A4F"
green = "#68C256"
yellow = "#DCCD51"
blue = "#1C98E8"
magenta = "#8E69C9"
cyan = "#1C98E8"
white = "#BABABA"

[colors.bright]
black = "#666666"
red = "#E05A4F"
green = "#77B869"
yellow = "#EFD64B"
blue = "#387CD3"
magenta = "#957BBE"
cyan = "#3D97E2"
white = "#BABABA"

[cursor.style]
shape = "Beam"

[colors.cursor]
cursor = "#a6a28c"
text = "#20201d"

[font]
size = 10

[font.normal]
family = "CodeNewRoman Nerd Font"

[window]
decorations = "None"
